### ISSUE TITLE
jq not found

### ISSUE THREAD

**Issue by subwolf** [xyphos10/StorjScripts#2]
You assume not only that I know what jq is, but that I can use it. Please include instructions on how to enable debugging so that such information on the health of the node is available.

**Comment by xyphos10** [comment]
Hello,

You do not need to enable debugging to use this script. I have in the readme.md stated that jq needs to be installed and can be done so by running the following command

sudo apt install jq

Please not this is for ubuntu and debian based systems.

**Comment by subwolf** [comment]
```
subwolf@localhost:~/StorjScripts$ uname -a
Linux localhost 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
subwolf@localhost:~/StorjScripts$ ./checkapi.sh
Scores are based on recent node performance, all time stats are provided for reference only
 subwolf@localhost:~/StorjScripts$ 
```
Yeah, really working, not.

**Comment by subwolf** [comment]
You assume that the server will be listening on 127.0.0.1:14002? What if its not?

**Comment by ReneSmeekes** [comment]
@subwolf that's the second question that is clearly mentioned in the readme

**Comment by xyphos10** [comment]
@subwolf, Hello, as is written in the readme which I have updated to make the requirements clearer, In order to run the script you will need to have the api port open. You do this by adding "-p 127.0.0.1:14002:14002" to your docker run command so it would end up like the example below. Again the script by default will try to get data from localhost port 14002 unless you specify otherwise. 

To add the port to the docker run command, you will have to stop the container, remove it and ren run the docker run command with the new option. The steps involved are:
1. docker stop -t 300 storagenode
2. docker rm storagenode
3. run your modified docker command eg docker run -d --restart unless-stopped -p 28967:28967 -p 127.0.0.1:14002:14002 etc etc etc
